Template.examplePage.helpers({
  activities: [
    'Amateur radio',
    'Acting',
    'Baton twirling',
    'Board games',
    'Book restoration',
    'Cabaret',
    'Calligraphy',
    'Candle making',
    'Computer programming',
    'Coffee roasting',
    'Cooking',
    'Coloring',
    'Cosplaying',
    'Couponing',
    'Creative writing',
    'Crocheting',
    'Cryptography',
    'Dance',
    'Digital arts',
    'Drama',
    'Drawing',
    'Do it yourself',
    'Electronics',
    'Embroidery',
    'Fashion',
    'Flower arranging',
    'Foreign language learning',
    'Gaming (tabletop games and role-playing games)',
    'Gambling',
    'Genealogy',
    'Glassblowing',
    'Gunsmithing',
    'Homebrewing',
    'Ice skating',
    'Jewelry making',
    'Jigsaw puzzles',
    'Juggling',
    'Knapping',
    'Knitting',
    'Kabaddi',
    'Knife making',
    'Lacemaking',
    'Lapidary',
    'Leather crafting',
    'Lego building',
    'Lockpicking',
    'Machining',
    'Macrame',
    'Metalworking',
    'Magic',
    'Model building',
    'Listening to music',
    'Origami',
    'Painting',
    'Playing musical instruments',
    'Pet',
    'Poi',
    'Pottery',
    'Puzzles',
    'Quilting',
    'Reading',
    'Scrapbooking',
    'Sculpting',
    'Sewing',
    'Singing',
    'Sketching',
    'Soapmaking',
    'Sports',
    'Stand-up comedy',
    'Sudoku',
    'Table tennis',
    'Taxidermy',
    'Video gaming',
    'Watching movies',
    'Web surfing',
    'Whittling',
    'Wood carving',
    'Woodworking',
    'Worldbuilding',
    'Writing',
    'Yoga',
    'Yo-yoing'
  ], 
});

Template.examplePage.events({
  'click .activity-link': function(event) {
    event.preventDefault();
    BrandFlakes.record(event.target.innerText);
  }
});
